export const sagaActions = {
  FETCH_USER_EVENTS: 'FETCH_USER_EVENTS',
  ADD_EVENT: 'ADD_EVENT',
  UPDATE_EVENT: 'UPDATE_EVENT',
  GET_EVENT: 'GET_EVENT',
  UPLOAD_IMAGE: 'UPLOAD_IMAGE',
  ADD_COMMENT: 'ADD_COMMENT',
}